name: objectbox_benchmark
description: Simple ObjectBox-Dart performance benchmark
publish_to: none

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  objectbox: any
  meta: ^1.3.0
  ffi: ^2.0.1

dev_dependencies:
  lints: ^3.0.0 # Requires Dart 3, but running analyzer only during development and with latest SDK
  objectbox_generator: any
  build_runner: any
